.TH QURAN\-CLI 1 October\ 2024 quran\-cli\-VERSION
.\".TH "QURAN-CLI" "1" "November 2024" "QURAN-CLI-VERSION"
.SH NAME
quran-cli \- A Qur'an from CLI
.SH SYNOPSIS
.B quran\-cli
.RB [ \-vf ]
.RB [ \-s
.IR surah ]
.RB [ \-a
.IR ayah ]
.SH  DESCRIPTION
A tiny Qur'an utility for CLI written in Go under 100 LOC.

.SH OPTIONS
.B \-v, \-\-version
Print version and exit
.TP
.B \-f, \-\-full\-text
Print the full text of the Qur'an to stdout and exit
.TP
.B \-s, \-\-surah=
Surah number
.TP
.B \-a, \-\-ayah=
Ayah number

.SH "AUTHOR"
.sp
Saif Shahriar
